// Module: dashboard — consolidated Playwright specs (4 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';
import { OrangeHRMPage } from '../../pages/orange-hrm/orange-hrm.page';

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("001 - Verify Dashboard basic information widgets render after successful login", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page.getByRole("heading", { name: "Dashboard" })).toContainText("Dashboard", { timeout: 15000 });
  await expect(page.getByText("Time at Work")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("My Actions")).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("Quick Launch")).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("002 - Verify unauthenticated direct access to Dashboard URL redirects to login", async ({ page }) => {
  await page.goto("/web/index.php/dashboard/index");
  await expect(page).toHaveURL(new RegExp("/auth/login"), { timeout: 15000 });
  await expect(page.getByRole("button", { name: "Login" })).toBeVisible({ timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/auth/login"), { timeout: 15000 });
  await expect(page.getByText("Dashboard", { exact: true })).toBeHidden({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("003 - Verify already-authenticated user visiting the login URL is routed to the Dashboard", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await page.goto("/web/index.php/auth/login");
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
});

test.describe('Dashboard Display', () => {
  test('004 - Verify Dashboard action after session expiry redirects to login', async ({ page }) => {
    const orangeHRM = new OrangeHRMPage(page);

    // 1. Log in as 'Admin' and remain on the Dashboard
    await orangeHRM.login('Admin', 'admin123');

    // 2. Invalidate the session by deleting the session cookie in developer tools (simulating session expiry)
    await page.context().clearCookies();

    // 3. Perform a Dashboard action that triggers a server request, such as clicking a navigation menu item
    await page.reload();

    // 4. Observe the resulting page
    await page.waitForURL((u) => u.toString().includes('/auth/login'), { timeout: 30000 });
    await expect(page).toHaveURL(/\/auth\/login/);
  });
});
