// Module: authentication — consolidated Playwright specs (4 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("001 - Verify successful login with valid credentials redirects to Dashboard", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("/dashboard"), { timeout: 15000 });
  await expect(page.getByRole("link", { name: "Dashboard" })).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("002 - Verify login fails with valid username and invalid password showing generic error", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("WrongPass999");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("https://opensource-demo\\.orangehrmlive\\.com/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("003 - Verify login fails with invalid username and valid password showing generic error", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("NonExistentUser01");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toBeVisible({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("004 - Verify pressing Enter with valid credentials triggers login", async ({ page }) => {
  await page.goto("/");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByPlaceholder("Password").press("Enter");
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
});
