// Module: authentication — consolidated Playwright specs (12 test cases).
// Generated by JBS IntelliQE. Tests are numbered sequentially within this file.

import { test, expect } from '@playwright/test';

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("001 - Verify successful login with valid credentials redirects to Dashboard", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page.getByRole("heading", { name: "Dashboard" })).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("002 - Verify 'Required' validation appears for both empty Username and Password on submit", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required", { exact: true }).nth(0)).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(0)).toContainText("Required", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true }).nth(1)).toContainText("Required", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("https://opensource-demo\\.orangehrmlive\\.com/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("003 - Verify 'Required' validation appears for empty Password when Username is filled", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true })).toContainText("Required", { timeout: 15000 });
  await expect(page.locator("input[name=\"username\"] ~ .oxd-input-field-error-message, .oxd-input-group:has(input[name=\"username\"]) .oxd-input-field-error-message")).toBeHidden({ timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("https://opensource-demo\\.orangehrmlive\\.com/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("004 - Verify 'Required' validation appears for empty Username when Password is filled", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Required")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Required", { exact: true })).toContainText("Required", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
  await expect(page.locator(".oxd-input-group:has(input[name=\"password\"]) .oxd-input-field-error-message")).toBeHidden({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("005 - Verify login fails with a valid username and an incorrect password", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("WrongPass999");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/auth/login"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("006 - Verify login with a non-existent username returns the same generic 'Invalid credentials' error as a wrong password", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("GhostUser404");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials", { exact: true })).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials", { exact: true })).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials", { exact: true })).toContainText("Invalid credentials", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials", { exact: true })).toContainText("Invalid credentials", { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("007 - Verify username field case sensitivity on login", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("008 - Verify login handling of leading and trailing whitespace in the Username field", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("  Admin  ");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page.getByText("Invalid credentials")).toContainText("", { timeout: 15000 });
  await expect(page.getByText("Invalid credentials")).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("009 - Verify password is not exposed in the URL or query string during login submission", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("dashboard"), { timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("010 - Verify rapid double-click on Login does not create duplicate sessions or errors", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page).toHaveURL(new RegExp("/web/index\\.php/dashboard/index"), { timeout: 15000 });
  await expect(page.getByRole("link", { name: "Dashboard" })).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole("link", { name: "Dashboard" })).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("011 - Verify 'Forgot your password?' link navigates to the password reset page", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await expect(page.getByText("Forgot your password?")).toBeVisible({ timeout: 15000 });
  await page.getByText("Forgot your password?").click();
  await expect(page).toHaveURL(new RegExp("/auth/requestPasswordResetCode"), { timeout: 15000 });
  await expect(page.getByPlaceholder("Username")).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole("button", { name: "Reset Password" })).toBeVisible({ timeout: 15000 });
  await expect(page.getByRole("button", { name: "Cancel" })).toBeVisible({ timeout: 15000 });
});

// Generated LIVE against the running application — every locator below was
// executed and verified in a real browser at generation time.
test("012 - Verify end-to-end journey from login through Dashboard basic information view", async ({ page }) => {
  await page.goto("/web/index.php/auth/login");
  await page.getByPlaceholder("Username").fill("Admin");
  await page.getByPlaceholder("Password").fill("admin123");
  await page.getByRole("button", { name: "Login" }).click();
  await expect(page).toHaveURL(new RegExp("/dashboard/index"), { timeout: 15000 });
  await expect(page.getByRole("heading", { name: "Dashboard" })).toContainText("Dashboard", { timeout: 15000 });
  await expect(page.getByText("Time at Work")).toBeVisible({ timeout: 15000 });
  await expect(page.getByText("My Actions")).toContainText("My Actions", { timeout: 15000 });
  await expect(page.getByText("Time at Work")).toBeVisible({ timeout: 15000 });
});
